# Generated by Django 5.1.1 on 2024-09-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='m_maestro',
            fields=[
                ('id_maestro', models.AutoField(db_column='id_maestro', primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
